### ISSUE TITLE
Error trying to start the gulp dev

### ISSUE THREAD

**Issue by Revod** [Xantier/nerd-stack#30]
Im newbie in this, but when i pu in the console "gulp dev" i get this error, why?
![sin titulo](https://cloud.githubusercontent.com/assets/10109689/8313193/19c55052-19ab-11e5-927c-efac21d23f5e.png)
![sin titulo 2](https://cloud.githubusercontent.com/assets/10109689/8313208/2d9f4182-19ab-11e5-912e-a7411bc8a611.png)
hope you help me, and thanks

**Comment by Xantier** [comment]
Oops, that's an import accidentally left in one of the JSX files that is not in use anymore. I'll push a fix to that now.

**Comment by Revod** [comment]
I Delete that line and get this
![sin titulo](https://cloud.githubusercontent.com/assets/10109689/8318300/420068a0-19cd-11e5-92e7-2d45e30d1d72.png)

Need delete other line?

**Comment by Xantier** [comment]
The application is trying to take a connection to a database but fails doing that. Double check your app/config/config.json that the DB of your choice is setup correctly and make sure that database is running.

**Comment by Revod** [comment]
Im using Windows 8.1 32 bits and MongoDB, node version v 0.12.4

**Comment by tMuhonen** [comment]
Would probably be a best to document the versions compatible and stick with
them for now or add polyfills. What you think Jussi?

**Comment by Xantier** [comment]
Yup, sounds good. I'll add a list of known working configs. Ship in pull requests of your systems if you have tested and deemed working. Let's continue on #32
