### ISSUE TITLE
How to create new migrations?

### ISSUE THREAD

**Issue by iit-federico-bozzini** [Xantier/nerd-stack#37]
Is it correct to say that at the moment this skeleton doesn't offer any basic way to create new migrations?

Apparently the only thing I'm able to find in the skeleton is a way to run the migrations created in some other way using knex. Is it correct?

**Comment by Xantier** [comment]
Hello Federico,

Yeah, at the moment migrations are through knex. I decided to leave those as is since I wasn't really certain what would be the best way forward for databases out of Bookshelfs reach. 

Do you have any suggestions of a good way to do them?

**Comment by Xantier** [comment]
Closing due to time out.
